---
abstract: 'A simple, foolproof, scanner/driver for Marpa'
author:
  - 'Andrew Rodland <arodland@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300018, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MarpaX-Lex-Easy
no_index: {}
requires:
  Data::Dumper: 0
  Moo: 0
  MooX::Types::MooseLike::Base: 0.16
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=MarpaX-Lex-Easy
  homepage: http://metacpan.org/release/MarpaX-Lex-Easy
  license: http://dev.perl.org/licenses/
  repository: git://github.com/arodland/MarpaX-Lex-Easy.git
version: 0.0000001
x_authority: cpan:ARODLAND
